baseURL = "https://kobecurryjapones.com/"
languageCode = "es-co"
title = "Kobe Curry de Armenia"
theme = "hugo-scroll"

[params]
    description = "Comida japonesa auténtica en Armenia, Quindío."
    # テーマが内部で使うSassの設定を明示的に追加
    [params.sass]
        fingerprint = true